version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "php ./database/migrate.php && php-fpm"
    image: bumerang-app
    container_name: bumerang-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./database:/var/www/database
    networks:
      - bumerang-network

  nginx:
    image: nginx:alpine
    container_name: bumerang-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - bumerang-network

networks:
  bumerang-network:
    driver: bridge
